[[vectorImages]]
[vectorImages.input]
filePath= "./webpageDesigns/index-macbook.svg"
[vectorImages.output]
viewAdderFunctionName= "indexPageMacbook"
directoryPath= "./src/inkscapeSVGGenerated"

# We can't handle that file yet
#
# [[vectorImages]]
# [vectorImages.input]
# filePath= "./circles_1920_by_1080.svg"
# [vectorImages.output]
# viewAdderFunctionName= "circles1920By1080"
# directoryPath= "./src/inkscapeSVGGenerated"
#
